version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Univer/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=universities;Username=postgres;Password=yourpassword

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: universities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
